### ISSUE TITLE
No need to configure compileJava/run

### ISSUE THREAD

**Issue by jperedadnr** [miho/ScaledFX#5]
The javafx plugin manages that for you.

You can remove this:
```
compileJava {
    doFirst {
        options.compilerArgs = [
                '--module-path', classpath.asPath,
                '--add-modules', 'javafx.controls'
        ]
    }
}

run {
    doFirst {
        jvmArgs = [
                '--module-path', classpath.asPath,
                '--add-modules', 'javafx.controls',
                "-Xmx12000m"
        ]
    }
}
```
and just add the extra options if needed:
```
run {
    doFirst {
        jvmArgs += ["-Xmx12000m" ]
    }
}
```

**Comment by miho** [comment]
Thanks. Good to know. Do you know how I can declare test-dependencies with the javafx plugin? Is that even possible right now?

**Comment by jperedadnr** [comment]
You mean something like `testModules = ['javafx.fxml']`, to declare other JavaFX modules that won't be part of the run task? This doesn't exist in the plugin (yet). 

There is a similar [issue](https://github.com/openjfx/javafx-gradle-plugin/issues/11), maybe you can clarify there.

**Comment by miho** [comment]
Yes. That's what I meant. I pointed out the importance of separate dependencies for each configuration in the issue you mentioned. Thanks for creating this issue. The build script looks much nicer now :)
